from __future__ import annotations

from functools import partial
from typing import TYPE_CHECKING, Literal

import isaaclab.utils.math as math_utils
import torch
from isaaclab.managers import ManagerTermBase, SceneEntityCfg

if TYPE_CHECKING:
    from isaaclab.assets import Articulation
    from isaaclab.envs import ManagerBasedEnv
    from isaaclab.managers import EventTermCfg


class apply_external_gravity_force(ManagerTermBase):
    """Randomize the external gravitational forces applied to an articulation's bodies at their CoMs.

    This term creates a set of force vectors aligned with the world's z-axis and applies them to
    each of the articulation's bodies at their CoMs. The forces are generated by sampling random
    gravity vectors uniformly within the given range and then scaling them by each body's mass.
    The forces are rotated by the orientation of each body's CoM and applied at the position's of
    the CoM itself. The shape of applied forces equals to (num_envs, num_bodies, 3). The forces are
    applied to the bodies by calling ``asset.set_external_force_and_torque``. The forces are only
    applied when ``asset.write_data_to_sim()`` is called in the environment.
    """

    def __init__(self, cfg: EventTermCfg, env: ManagerBasedEnv):
        """Initialize the term
        Args:
            cfg: The configuration of the event term.
            env: The environment instance.
        """
        super().__init__(cfg, env)
        # prepare asset quantities needed for randomization
        asset_cfg: SceneEntityCfg = cfg.params["asset_cfg"]
        asset: Articulation = env.scene[asset_cfg.name]
        self.body_ids = (
            torch.tensor(asset_cfg.body_ids, dtype=torch.int)
            if asset_cfg.body_ids != slice(None)
            else torch.arange(asset.num_bodies)
        )
        self.body_masses = asset.data.default_mass[:, self.body_ids, None]
        self.body_ids = self.body_ids.to(device=env.device)
        self.body_masses = self.body_masses.to(device=env.device)

        # initialize function for random sampling gravity's magnitude
        distribution: Literal["uniform", "log_uniform", "gaussian"] = cfg.params["distribution"]
        dp1, dp2 = cfg.params["distribution_params"]
        match distribution:
            case "uniform":
                self.sample_fn = partial(
                    math_utils.sample_uniform, lower=dp1, upper=dp2, device=env.device
                )
            case "log_uniform":
                self.sample_fn = partial(
                    math_utils.sample_log_uniform, lower=dp1, upper=dp2, device=env.device
                )
            case "gaussian":
                self.sample_fn = partial(
                    math_utils.sample_gaussian, mean=dp1, std=dp2, device=env.device
                )

    def __call__(
        self,
        env: ManagerBasedEnv,
        env_ids: torch.Tensor | None,
        asset_cfg: SceneEntityCfg,
        distribution_params: tuple[float, float],
        distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
    ) -> None:
        """Randomize the external gravitational forces applied to an articulation's bodies at their CoMs.

        Args:
            env: The environment instance.
            env_ids: Environment indices to update external forces for.
            asset_cfg: Asset configuration for articulation asset to apply forces to.
            distribution_params: random distribution parameters. If distribution is `uniform` or
                `log_uniform` then these correspond to the `lower` and `upper` parameters.
                Otherwise, they represent the `mean` and `std` parameters of the Gaussian
                distribution.
            distribution: Type of distribution to sample gravity magnitude's from.
        """
        # extract asset
        asset: Articulation = env.scene[asset_cfg.name]
        env_ids = torch.arange(env.num_envs, device=env.device) if env_ids is None else env_ids

        # sample gravity's magnitude and convert to a gravity vector
        gravity = self.sample_fn(size=(len(env_ids,)))  # fmt: skip
        gravity = torch.stack(
            [torch.zeros_like(gravity), torch.zeros_like(gravity), gravity], dim=1
        )
        # convert gravity vectors to per-body force vectors
        forces = gravity[:, None, :] * self.body_masses[env_ids]

        # rotate forces by body link orientation
        link_quat_w = asset.data.body_link_quat_w[env_ids][:, self.body_ids]
        forces = math_utils.quat_apply_inverse(link_quat_w, forces)

        # apply forces to asset at body CoMs
        com_pos_b = asset.data.body_com_pos_b[env_ids][:, self.body_ids]
        asset.set_external_force_and_torque(
            forces,
            torch.zeros_like(forces),
            positions=com_pos_b,
            body_ids=self.body_ids,
            env_ids=env_ids,
            is_global=False,
        )
